FourEngineeringForum/Models/Topico.cs
using System;
using System.Collections.Generic;

namespace FourEngineeringForum.Models
{
    public class Topico
    {
        public Topico()
        {
            this.Postagem = new List<Postagem>();
        }

        public int ID { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public DateTime DataDeCadastro { get; set; }
        public virtual IList<Postagem> Postagem { get; set; }
    }
}

FourEngineeringForum/Controllers/PostagemController.cs
using FourEngineeringForum.Config;
using FourEngineeringForum.Models;
using FourEngineeringForum.Repositorio;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace FourEngineeringForum.Controllers
{
    [VerificaUsuarioLogado]
    public class PostagemController : Controller
    {
        private ForumDbContext db = new ForumDbContext();

        /// <summary>
        /// Método responsável por exibir uma lista de Postagens cadastradas
        /// </summary>
        /// <param name="idDoTopico">Identificador da Postagem</param>
        /// <returns>ActionResult</returns>
        public ActionResult Index(int? idDoTopico)
        {
            var nomeTopico = db.Topicos.Find(idDoTopico);
            var postagem = db.Postagens.Where(p => p.Topico.ID == idDoTopico).Include(p => p.Topico).Include(p => p.Usuario);
            postagem.Count();

            if (nomeTopico != null)
            {
                ViewBag.Nome = nomeTopico.Nome;
            }

            return View(postagem);
        }

        /// <summary>
        /// Método responsável por preencher um selectList com Tópicos e Usuários cadastrados
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult Adicionar()
        {
            ViewBag.IdDoTopico = new SelectList(db.Topicos, "ID", "Nome");
            ViewBag.IdDoUsuario = new SelectList(db.Usuarios, "ID", "Nome");
            return View();
        }

        /// <summary>
        /// Método responsável por salvar uma nova Postagem
        /// </summary>
        /// <param name="postagem">Postagem</param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar([Bind(Include = "ID,IdDoTopico,IdDoUsuario,Mensagem,DataDePublicacao")] Postagem postagem)
        {
            if (ModelState.IsValid)
            {
                Usuario usuarioLogado = AutenticarUsuario.RetornarUsuarioDaSessao();

                postagem.IdDoUsuario = usuarioLogado.ID;
                postagem.DataDePublicacao = DateTime.Now;

                db.Postagens.Add(postagem);
                db.SaveChanges();

                return RedirectToAction("Index", new { idDoTopico = postagem.IdDoTopico });
            }

            ViewBag.IdDoTopico = new SelectList(db.Topicos, "idDoTopico", "nome", postagem.IdDoTopico);
            ViewBag.IdDoUsuario = new SelectList(db.Usuarios, "idDoUsuario", "Nome", postagem.IdDoUsuario);
            return View(postagem);
        }

        /// <summary>
        /// Método responsável por exibir na tela, dados do post que serão editados
        /// </summary>
        /// <param name="idDoPost">ID</param>
        /// <returns>Exibe dados do post ou redireciona para a página de login</returns>>
        public ActionResult Editar(int? idDoPost)
        {
            if (AutenticarUsuario.VerificarSessaoUsuario())
            {
                if (idDoPost == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Postagem post = db.Postagens.Find(idDoPost);
                if (post == null)
                {
                    return HttpNotFound();
                }
                return View(post);
            }
            return Redirect("/Login");
        }

        /// <summary>
        /// Método responsável por editar os dados do post e gravar no banco de dados
        /// </summary>
        /// <param name="post">Usuário</param>
        /// <returns>Exibe dados do post ou redireciona para a página de login</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Postagem post)
        {
            if (AutenticarUsuario.VerificarSessaoUsuario())
            {
                if (ModelState.IsValid)
                {
                    db.Entry(post).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index", new { idDoTopico = post.IdDoTopico });
                }
                return View(post);
            }
            return Redirect("/Login");
        }

        /// <summary>
        /// Método responsável por fazer a chamada do Garbage Colector e limpar objetos não utilizados da memória
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FourEngineeringForum/Controllers/TopicoController.cs
using FourEngineeringForum.Config;
using FourEngineeringForum.Models;
using FourEngineeringForum.Repositorio;
using System.Linq;
using System.Web.Mvc;

namespace FourEngineeringForum.Controllers
{
    [VerificaUsuarioLogado]
    public class TopicoController : Controller
    {
        private ForumDbContext db = new ForumDbContext();

        /// <summary>
        /// Método responsável por listar todos os Tópicos
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult Index()
        {
            return View(db.Topicos.ToList());
        }

        /// <summary>
        /// Método responsavel por exibir a tela de novo Tópico
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult Adicionar()
        {
            return View();
        }

        /// <summary>
        /// Método responsável por adicionar um novo Tópico
        /// </summary>
        /// <param name="topico">Tópico</param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar([Bind(Include = "ID,Nome,Descricao,DataDeCadastro")] Topico topico)
        {
            if (ModelState.IsValid)
            {
                db.Topicos.Add(topico);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(topico);
        }

        /// <summary>
        /// Método responsável por fazer a chamada do Garbage Colector e limpar objetos não utilizados da memória
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FourEngineeringForum/Views/Topico/Adicionar.cshtml
@model FourEngineeringForum.Models.Topico
@{
    ViewBag.Title = "Cadastrar Novo Tópico";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label for="Nome" class="control-label col-md-2">Nome</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="Descricao" class="control-label col-md-2">Descrição</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" , @required = "required" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="data" class="control-label col-md-2">Data cadastro</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DataDeCadastro, new { @class = "form-control", @Value = DateTime.Now.ToString("dd/MM/yyyy"), disabled = true })
                @Html.ValidationMessageFor(model => model.DataDeCadastro, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Voltar", "Index", null, null, new { @class = "btn btn-info" })
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

FourEngineeringForum/Views/Topico/Index.cshtml
@model IEnumerable<FourEngineeringForum.Models.Topico>

@{
    ViewBag.Title = "Lista de Tópicos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title</h2>
<hr />

<div class="form-group">
    @if (Convert.ToInt16(Session["perfilDoUsuario"]) == 0)
    {
        @Html.ActionLink("Cadastro", "Adicionar", null, null, new { @class = "btn btn-primary" })

    }
    else
    {
        <span style="font-style:italic">(Somente Administrador pode criar novo Topico)</span>
    }
</div>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td> @Html.DisplayFor(modelItem => item.Nome) </td>
            <td> @Html.DisplayFor(modelItem => item.Descricao) </td>
            <td>
                @Html.ActionLink("Visualizar Tópico", "Index", "Postagem", new { idDoTopico = item.ID }, null)
        </tr>
    }
</table>